---
- hosts: all
  become: yes
  become_method: sudo


  vars_files:
    - vars/users.yaml


  pre_tasks:

    - name: Creating Common Good IT team users (from Github)
      debug:
        msg: extracted (2021-11-26) from https://github.com/orgs/common-good/teams/team-cg-it


  roles:

    - { role: geerlingguy.github-users }


  tasks:

    # based on: https://lebenplusplus.de/2017/04/19/creating-users-and-their-passwords-with-ansible/

    - name: Unlock password and set it to empty
      command: passwd -d "{{ item.name }}"
      with_items: "{{ github_users }}"

    - name: Expire password
      command: chage -d 0 "{{ item.name }}"
      with_items: "{{ github_users }}"

